python: 3.10.6
dependencies:
- absl-py==1.2.0
- adjustText==1.0.4
- argon2-cffi==21.3.0
- argon2-cffi-bindings==21.2.0
- asttokens==2.0.5
- astunparse==1.6.3
- attrs==22.1.0
- backcall==0.2.0
- basemap==1.3.7
- basemap-data==1.3.2
- beautifulsoup4==4.11.1
- biogeme==3.2.10
- bleach==5.0.1
- branca==0.7.1
- bs4==0.0.1
- cachetools==5.2.0
- Cartopy==0.22.0
- catboost==1.2.2
- certifi==2022.6.15
- cffi==1.15.1
- charset-normalizer==2.1.0
- cloudpickle==3.0.0
- cmdstanpy==1.1.0
- colorama==0.4.5
- convertdate==2.4.0
- cycler==0.11.0
- Cython==0.29.33
- DateTime==5.0
- debugpy==1.6.2
- decorator==5.1.1
- defusedxml==0.7.1
- dtw==1.4.0
- entrypoints==0.4
- ephem==4.1.4
- et-xmlfile==1.1.0
- executing==0.9.1
- fastjsonschema==2.16.1
- filelock==3.13.1
- flatbuffers==1.12
- folium==0.15.1
- fonttools==4.34.4
- fsspec==2023.12.2
- gast==0.4.0
- geographiclib==2.0
- geopy==2.4.1
- google-auth==2.9.1
- google-auth-oauthlib==0.4.6
- google-pasta==0.2.0
- graphviz==0.20.1
- grpcio==1.48.0
- gurobipy==11.0.0
- gym==0.26.2
- gym-notices==0.0.8
- h5py==3.7.0
- hijri-converter==2.2.4
- holidays==0.21.13
- idna==3.3
- intel-openmp==2021.4.0
- ipykernel==6.15.1
- ipython==8.4.0
- ipython-genutils==0.2.0
- ipywidgets==7.7.1
- jedi==0.18.1
- Jinja2==3.1.2
- joblib==1.2.0
- jsonschema==4.9.1
- jupyter==1.0.0
- jupyter-client==7.3.4
- jupyter-console==6.4.4
- jupyter-core==4.11.1
- jupyterlab-pygments==0.2.2
- jupyterlab-widgets==1.1.1
- kaleido==0.2.1
- keras==2.9.0
- Keras-Preprocessing==1.1.2
- kiwisolver==1.4.4
- korean-lunar-calendar==0.3.1
- legacy==0.1.6
- libclang==14.0.6
- llvmlite==0.41.1
- LunarCalendar==0.0.9
- lxml==5.1.0
- Markdown==3.4.1
- MarkupSafe==2.1.1
- matlab==0.1
- matlabengine==9.14.3
- matlabengineforpython==9.14
- matplotlib==3.5.2
- matplotlib-inline==0.1.3
- mistune==0.8.4
- mkl==2021.4.0
- mpmath==1.3.0
- nbclient==0.6.6
- nbconvert==6.5.0
- nbformat==5.4.0
- nest-asyncio==1.5.5
- networkx==3.2.1
- notebook==6.4.12
- numba==0.58.1
- numpy==1.23.1
- oauthlib==3.2.0
- openpyxl==3.0.10
- opt-einsum==3.3.0
- packaging==21.3
- palettable==3.3.3
- pandas==1.4.3
- pandas-datareader==0.10.0
- pandocfilters==1.5.0
- parso==0.8.3
- pathvalidate==3.2.0
- patsy==0.5.3
- pickleshare==0.7.5
- Pillow==9.2.0
- plotly==5.12.0
- prometheus-client==0.14.1
- prompt-toolkit==3.0.30
- prophet==1.1.2
- protobuf==3.19.4
- psutil==5.9.1
- pure-eval==0.2.2
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pyaviation==0.0.2
- pycountry==23.12.11
- pycparser==2.21
- pygame==2.3.0
- Pygments==2.12.0
- PyMeeus==0.5.12
- pyparsing==3.0.9
- pyproj==3.5.0
- PyQt5==5.15.9
- PyQt5-Qt5==5.15.2
- PyQt5-sip==12.11.1
- pyrsistent==0.18.1
- pyshp==2.3.1
- python-dateutil==2.8.2
- pytorch-tabnet==4.1.0
- pytz==2022.1
- pywin32==304
- pywinpty==2.0.7
- pyzmq==23.2.0
- qtconsole==5.3.1
- QtPy==2.1.0
- requests==2.28.1
- requests-oauthlib==1.3.1
- rsa==4.9
- scikit-learn==1.2.2
- scikit-learn-extra==0.3.0
- scipy==1.9.3
- seaborn==0.12.2
- Send2Trash==1.8.0
- setuptools-git==1.2
- shap==0.44.0
- shapely==2.0.3
- six==1.16.0
- sklearn==0.0.post1
- slicer==0.0.7
- soupsieve==2.3.2.post1
- stack-data==0.3.0
- statsmodels==0.13.5
- sympy==1.12
- tbb==2021.6.0
- tenacity==8.1.0
- tensorboard==2.9.1
- tensorboard-data-server==0.6.1
- tensorboard-plugin-wit==1.8.1
- tensorflow==2.9.1
- tensorflow-estimator==2.9.0
- tensorflow-gpu==2.9.1
- tensorflow-io-gcs-filesystem==0.26.0
- termcolor==1.1.0
- terminado==0.15.0
- threadpoolctl==3.1.0
- tinycss2==1.1.1
- tobii-research==1.11.0
- torch==2.3.0
- torchdata==0.7.1
- torchinfo==1.8.0
- torchvision==0.18.0
- tornado==6.2
- tqdm==4.64.1
- traitlets==5.3.0
- tslearn==0.6.3
- typing_extensions==4.12.1
- tzdata==2022.7
- urllib3==1.26.11
- wcwidth==0.2.5
- webencodings==0.5.1
- Werkzeug==2.2.1
- widgetsnbextension==3.6.1
- winshell==0.6
- wrapt==1.14.1
- xgboost==2.0.0
- xlrd==2.0.1
- xyzservices==2023.10.1
- zope.interface==5.5.2
